routes/admin.php
<?php

// admin

Route::get('/dash', 'Dashboard\DashboardController@index');

// receipts :-
Route::resource('/tripReceipt', 'tripReceipt\IndexController');
Route::get('/applyRepresentative/{id}', 'tripReceipt\IndexController@applyRepresentative');
Route::post('/saveApplyRepresentative', 'tripReceipt\IndexController@saveApplyRepresentative');


// meeting_requests
Route::get('/meeting_requests', 'Trip\meetingRequest\IndexController@index');

Route::resource('/openScreens', 'openScreen\IndexController');

// pending children
Route::get('/pending_children', 'Child\Pending_trip\IndexController@index');
Route::get('/assign_drivers/{id}', 'Child\Pending_trip\IndexController@assign_drivers');
Route::post('/child_assign_drivers', 'Child\Pending_trip\IndexController@child_assign_drivers');
Route::get('/pending_child_map_location/{id}', 'Child\Pending_trip\IndexController@pending_child_map_location');

// Plans
Route::resource('/plans', 'Plan\IndexController');
Route::resource('/plans.vouchers', 'PlansVoucher\IndexController');
Route::get('/DeactivatePlan/{id}', 'Plan\ActionController@DeactivatePlan');
Route::get('/activatePlan/{id}', 'Plan\ActionController@activatePlan');

// Review List
Route::get('/getReviews/{id}', 'Review\IndexController@index');

// order
Route::resource('/orders', 'Order\IndexController');
Route::get('/orders/{id}/reject', 'Order\IndexController@reject');
Route::post('/orders/{id}/reject', 'Order\IndexController@doReject');
Route::resource('/order_status', 'Order\OrderStatusController');
Route::get('/order_client_drivers_responded/{id}', 'Order\IndexController@responded');

Route::resource('/users', 'User\IndexController');
Route::get('/userVoucher/{id}', 'User\VoucherController@index');
Route::get('/familyMembers/{id}', 'User\Family\IndexController@index');
Route::get('/users_not_answer_drivers_request', 'User\Family\IndexController@users_not_answer_drivers_request');
Route::resource('/users.children', 'User\userChildrenController');
Route::resource('/users.familyMembers', 'User\userFamilyMembersController');
Route::resource('/users.wallet_details', 'User\userWalletController');
Route::resource('/users.points', 'User\userPointsController');
Route::resource('/users.single_rides', 'User\userSingleRideController');
Route::resource('/users.favourite_places', 'User\userFavouritePlacesController');
Route::get('/placeLocation/{id}', 'User\userFavouritePlacesController@location');
Route::resource('/countries', 'Country\IndexController');
Route::resource('/countries.start_with', 'Country\StartWith\IndexController');
Route::resource('/countries.cities', 'Country\City\IndexController');
Route::resource('/cities', 'City\IndexController');
Route::resource('/districts', 'District\IndexController');
Route::resource('/terms', 'Term\IndexController');

Route::get('/userNotifiy/{id}', 'User\UserNotificationController@index');
Route::post('/userNotifiyStore', 'User\UserNotificationController@userNotifiyStore');
// Relations
Route::resource('/relations', 'Relation\IndexController');

// Slider User , Driver
Route::resource('/sliders', 'Slider\IndexController');
Route::resource('/sliders.click', 'SliderClicks\IndexController');
Route::resource('/user_slider', 'Slider\UserSliderController');
Route::resource('/driver_slider', 'Slider\DriverSliderController');

Route::resource('/order_car_types', 'Order\carType\IndexController');
Route::resource('/car_types', 'carType\IndexController');
Route::resource('/car_names', 'CarName\IndexController');
Route::resource('/education_types', 'EducationType\IndexController');
Route::resource('/levels', 'Level\IndexController');
Route::resource('/stages', 'Stage\IndexController');
Route::resource('/manufacturing_years', 'ManufacturingYear\IndexController');
Route::resource('/payment_types', 'PaymentType\IndexController');
Route::resource('/schools', 'School\IndexController');
Route::resource('/schools.levels', 'School\Level\IndexController');
Route::resource('/schoolLevels.school_times', 'SchoolTime\IndexController'); // stages
Route::resource('/school_times_stages.holidays', 'SchoolTimeStages\IndexController'); // stages holidays
Route::resource('/stage_holidays.days', 'StageHolidayDays\IndexController'); // stages holidays Days


Route::get('/schoolsAddress/{id}', 'School\IndexController@address');


// Driver Side
Route::resource('/drivers', 'Driver\IndexController');
Route::get('/active_drivers', 'Driver\FilterController@active_drivers');
Route::get('/waiting_drivers', 'Driver\FilterController@waiting_drivers');
Route::get('/block_drivers', 'Driver\FilterController@block_drivers');

// Driver Singlr Ride
Route::resource('/drivers.single_rides', 'Driver\SingleRide\DriverSingleRideController');


//Driver
Route::resource('/drivers.orders', 'Driver\Order\IndexController');
Route::resource('/drivers.districts', 'Driver\City\IndexController');
Route::resource('/drivers.criming_recorder', 'Driver\CrimingRecorder\IndexController');
Route::resource('/drivers.driving_licences', 'Driver\DrivingLicences\IndexController');
Route::resource('/drivers.driving_car_licences', 'Driver\DrivingCarLicences\IndexController');
Route::resource('/drivers.driving_car_images', 'Driver\DrivingCarImages\IndexController');
Route::resource('/drivers.driver_identities', 'Driver\DriverIdentities\IndexController');
Route::resource('/drivers.driver_reports', 'Driver\DriverReports\IndexController');
Route::resource('/drivers.driver_share_infos', 'Driver\driverShareInfo\IndexController');
Route::get('/drivers_driving_license_block/{id}', 'Driver\BlockController@index');

// Active , deActive accounts ( user , Driver )
Route::get('/active_account/{id}', 'Driver\ActiveAccountController@index');
Route::get('/drActive_account/{id}', 'Driver\ActiveAccountController@drActive_account');

// delete , return ( Child Account ).
Route::get('/retuen_account/{id}', 'Child\AccountController@index');
Route::get('/delete_account/{id}', 'Child\AccountController@delete_account');


// Trip
Route::resource('/trips', 'Trip\IndexController');
Route::resource('/trips.children', 'TripChildren\IndexController');
Route::resource('/trips.rides', 'TripRide\IndexController');
//    Route::get('/TripChildren/{id}', 'Trip\IndexController@TripChildren');

//trips_ride_status
Route::resource('/trips_ride_status', 'TripsRideStatus\IndexController');


// Attach
Route::get('/attach/{id}/school/{school_id}', 'Attach\IndexController@index');
Route::get('/order/{order_id}/attach/{trip_id}/store', 'Attach\IndexController@store');
Route::post('/addTripsWithDrivers', 'Trip\TripWithDriver\IndexController@index');

//voucher
Route::resource('/voucher-type', 'Voucher_type\IndexController');
Route::resource('/voucher', 'Voucher\IndexController');
Route::resource('/voucher.plans', 'VoucherPlans\IndexController');
Route::resource('/voucher.user', 'VoucherUser\IndexController');


// Month
Route::resource('/months', 'Month\IndexController');
Route::resource('/months.days', 'Day\IndexController');

// Tax
Route::resource('/tax_type', 'TaxType\IndexController');
Route::resource('/taxes', 'Tax\IndexController');


Route::resource('/weather_messages', 'Weather\IndexController');

// Notifications
Route::resource('/notifications', 'Notification\IndexController');

// Representative
Route::resource('/representative', 'Representative\IndexController');
Route::resource('/representative.districts', 'Representative\City\IndexController');

// redeem
Route::resource('/redeems', 'Redeem\IndexController');
Route::resource('/points', 'Point\IndexController');

// brands
Route::resource('/brands', 'Brand\IndexController');
// salary Packages
Route::resource('/salary_packages', 'SalaryPackage\IndexController');

Route::get('/afterSchool/{id}', 'afterSchool\IndexController@index');

// commissary
Route::resource('/commissary_reasons', 'Commissary\ReasonController');
Route::resource('/users.commissaries', 'Commissary\IndexController');
Route::get('/ConfirmCommissary/{id}', 'Commissary\IndexController@ConfirmCommissary');


//contacts
Route::resource('/contacts', 'ContactUs\IndexController');


//setting
Route::resource('/setting', 'Setting\IndexController');//

Route::get('/users/{id}/block', 'User\IndexController@block');

Route::get('/deblock/{id}', 'User\IndexController@deblock');

Auth::routes();

routes/web.php
<?php


Route::get('/admin', 'Admin\Auth\LoginController@index');
Route::post('/adminlogin', 'Admin\Auth\LoginController@adminlogin');
Route::post('/adminlogout', 'Admin\Auth\LoginController@adminlogout');


Route::get('/clear', function() {
    Artisan::call('cache:clear');
    session()->flash('success',trans('Cache has bees cleared successfully.'));
    return redirect('/');
});

// Site Routetes
    Route::get('/', 'Site\Home\indexController@index');

    // Ajax Controller
    Route::post('/getLevels', 'Admin\Ajax\IndexController@getLevels');
    Route::post('/getSchoolTimes', 'Admin\Ajax\IndexController@getSchoolTimes');
    Route::post('/getCities', 'Admin\Ajax\IndexController@getCities');
    Route::post('/getDistracts', 'Admin\Ajax\IndexController@getDistracts');
    Route::post('/getDistractDetails', 'Admin\Ajax\IndexController@getDistractDetails');

    // Slider count click
    Route::get('/openLink/{user_id}/{slider_id}', 'Site\Home\indexController@openLink');

Auth::routes();

app/Plan.php
<?php

namespace App;

use App\ModulesConst\NotificationTyps;
use App\ModulesConst\PlanTyps;
use Illuminate\Database\Eloquent\Model;

class Plan extends Model
{
    protected $fillable = [
        'name_ar',
        'name_en',
        'period',
        'discount',
        'status',
        'month_count',
    ];

    public function toArray()
    {
        $data['id'] = $this->id;
        $data['name'] = $this->serv_name;
        $data['period'] = $this->period;
        $data['discount'] = $this->discount;
        $data['month_count'] = $this->month_count;
        $data['price_per_kilo'] = $this->serv_price_per_kilo;
        $data['price_after_tax'] = $this->price_after_tax;
        return $data;
    }

    public function getServNameAttribute()
    {
        if (\request()->lang == "en")
            return $this->name_en;
        else
            return $this->name_ar;
    }

    public function getServPricePerKiloAttribute()
    {
        $pricePerKilo = KiloPerPrice::latest()->first();
        if (!$pricePerKilo) {
            $pricePerKilo = 0;
        }
        return $pricePerKilo->price;
    }

    public function getDashNameAttribute()
    {
        if (app()->getLocale() == "en")
            return $this->name_en;
        else
            return $this->name_ar;
    }



}

app/Trip.php
<?php

namespace App;

use App\Http\Resources\DriverAuth\DriverProfileResource;
use App\ModulesConst\TripStatus;
use Illuminate\Database\Eloquent\Model;

class Trip extends Model
{
    protected $fillable = [
        'school_id',
        'driver_id',
        'status'
    ];


    public function toArray()
    {
        $data['id'] = $this->id;
//            $data['driver'] = $this->driver;
        $data['driver'] = $this->driver_id ? DriverProfileResource::make($this->driver) : null;
        $data['school'] = $this->school;
//            $data['status_id'] = $this->status;
//            $data['status'] = $this->serv_status_name;
        $data['children'] = $this->children;
        $data['ride_status'] = $this->serv_ride_status_name;
        $data['ride_status_name'] = $this->ride_status_name();
        $data['ride_time'] = $this->serv_ride_time;
        $data['is_exist_ride'] = $this->is_exist_ride();
        $data['safety_details'] = About_app::first()->safety_details;

        return $data;
    }

    public function school()
    {
        return $this->belongsTo(School::class, 'school_id');
    }


    public function driver()
    {
        return $this->belongsTo(User::class, 'driver_id');
    }

    public function children()
    {
        return $this->hasMany(Trip_children::class, 'trip_id');
    }


    public function getServStatusAttribute()
    {
        $latest_ride = Trip_ride_life_cycle::where('trip_id', $this->id)->latest()->first();
        if ($latest_ride) {
            $status = $latest_ride->ride_status;
            return $status;
        }
        return __('language.schooltripName') . ' ( ' . $this->school->dash_name . ' ) ';
    }

    public function getServRideStatusNameAttribute()
    {
        $latest_ride = Trip_ride_life_cycle::where('trip_id', $this->id)->latest()->first();
        if ($latest_ride) {
            $status = $latest_ride->ride_status;
            return $status;
        }
        return null;
    }

    public function getDashDriverNameAttribute()
    {
        $attribute = __('language.notSelected');
        if ($this->driver) {
            $attribute = $this->driver->name;
        }
        return $attribute;
    }

    public function getDashSchoolNameAttribute()
    {
        $attribute = __('language.notSelected');
        if ($this->school) {
            $attribute = $this->school->dash_name;
        }
        return $attribute;
    }

    public function getDashChildrenCountAttribute()
    {
        $attribute = __('language.notSelected');
        if ($this->children) {
            $attribute = count($this->children);
        }
        return $attribute;
    }

    public function getDashStatusNameAttribute()
    {
        $latest_ride = Trip_ride_life_cycle::where('trip_id', $this->id)->latest()->first();
        if ($latest_ride) {
            $status = $latest_ride->ride_status;
            return $status->dash_name;
        }
        return __('language.schooltripName') . ' ( ' . $this->school->dash_name . ' ) ';
    }

    public function getDashRideTimeAttribute()
    {
        $latest_ride = Trip_ride_life_cycle::where('trip_id', $this->id)->latest()->first();
        if ($latest_ride) {
            $time = $latest_ride->getTime();
            return $time;
        }
        return __('language.notSelected');
    }

    public function getServRideTimeAttribute()
    {
        $latest_ride = Trip_ride_life_cycle::where('trip_id', $this->id)->latest()->first();
        if ($latest_ride) {
            $time = strtotime($latest_ride->created_at) * 1000;
            return $time;
        }
        return null;
    }


    public function ride_status_name()
    {
        $latest_ride = Trip_ride_life_cycle::where('trip_id', $this->id)->latest()->first();
        if ($latest_ride) {
            $status = $latest_ride->ride_status;
            if (!$status)
                return __('language.schooltripName') . ' ( ' . $this->school->dash_name . ' ) ';

            return $status->serv_name;
        }
        return __('language.schooltripName') . ' ( ' . $this->school->dash_name . ' ) ';
    }

    public function is_exist_ride()
    {
        $latest_ride = Trip_ride_life_cycle::where('trip_id', $this->id)->latest()->first();
        if ($latest_ride) {
            return true;
        }
        return false;
    }


    public function getRideStatusID()
    {
        $latest_ride = Trip_ride_life_cycle::where('trip_id', $this->id)->latest()->first();
        if ($latest_ride) {
            $status = $latest_ride;
            return $status->trip_ride_status_id;
        }
        return null;
    }


}

app/Http/Controllers/Admin/User/Family/IndexController.php
<?php

namespace App\Http\Controllers\Admin\User\Family;

use App\Child;
use App\Family_members;
use App\ModulesConst\AssignedStatus;
use App\ModulesConst\Paginate;
use App\User;
use App\User_assigin_trips;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class IndexController extends Controller
{
    public function index($id)
    {
        $user = User::find($id);
        $family_members_ids = Family_members::where('user_id', $id)->pluck('member_id');
        $family_members = User::whereIn('id', $family_members_ids)->get();
        $children = Child::where('user_id', $id)->orderBy('id', 'desc')->get();
        return view('admin.users.family.index', compact('family_members', 'children', 'user'));
    }

    public function users_not_answer_drivers_request()
    {
        $items = User_assigin_trips::where('status_id', AssignedStatus::pending)->orderBy('id', 'desc')->paginate(30);
        return view('admin.users.not_answer_drivers', compact('items'));
    }
}

app/Http/Controllers/Admin/User/VoucherController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\UserVoucher;
use App\Voucher;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class VoucherController extends Controller
{
    public function index(Request $request , $id){

        $ids = UserVoucher::where('user_id',$id)->pluck('voucher_id')->unique();
        $items = Voucher::whereIn('id', $ids)->orderBy('id', 'desc')->paginate(10);
        return view('admin.users.vouchers.index', compact('items'));
    }
}

app/Http/Controllers/Api/User/Children/ChildProfileController.php
<?php

    namespace App\Http\Controllers\Api\User\Children;

    use App\Child;
    use App\Traits\apiResponse;
    use App\User;
    use Illuminate\Http\Request;
    use App\Http\Controllers\Controller;

    class ChildProfileController extends Controller
    {
        use apiResponse;

        public function index(Request $request)
        {
            $request->validate([
                'child_id' => 'required'
            ]);

            $child = Child::find($request->child_id);
            return $this->apiResponse($request, trans('language.message'), $child, true);
        }
    }

resources/views/admin/users/family/create.blade.php
@extends('admin.layout.forms.add.index')
@section('action' , "users/$user->id/familyMembers")
@section('title' , trans('language.add'))
@section('page-title',trans('language.familyMembers'))
@section('form-groups')

    @includeIf('admin.components.form.add.select', ['label' => trans("language.relations"),'name'=>'user_relation_id', 'items'=> \App\User_relation::all() , 'icon' => 'fa fa-list',])
    @includeIf('admin.components.form.add.file', ['icon' => 'fa fa-image','label' => trans('language.image'),'name'=>'image', 'max'=>'2'])
    @includeIf('admin.components.form.add.text', ['icon' => 'fa fa-pencil','label' => trans('language.name'),'name'=>'name', 'placeholder'=>trans('language.name')])
    @includeIf('admin.components.form.add.text', ['icon' => 'fa fa-email','label' => trans('language.email'),'name'=>'email', 'placeholder'=>trans('language.email')])
    @includeIf('admin.components.form.add.text', ['icon' => 'fa fa-mobile','label' => trans('language.mobile'),'name'=>'mobile', 'placeholder'=>trans('language.mobile')])

@endsection
@section('submit-button-title' ,trans('language.add'))

resources/views/admin/users/family/index.blade.php
@extends('admin.layout.index')
@section('page-title',trans('language.users'))
@section('root' , "users")
@section('nav')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{url("admin/")}}">  {{trans('language.home')}}</a></li>
        <li class="breadcrumb-item"><a
                href="{{url("admin/users")}}">  {{trans('language.users')}}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{trans('language.children')}}</li>
    </ol>
@endsection
@section('content')

<div class="container-fluid">
    @if(count($family_members) > 0 )
        <div class="row el-element-overlay">
            <div class="col-md-12">
                <a href="{{url("admin/users/$user->id/familyMembers")}}" class="btn btn-info">
                    <h5 style="color: white ">{{trans('language.add') . ' ' . trans('language.family_members')}}</h5>
                </a>
                <br>
                <br>
            </div>

                @foreach ($family_members as $family_member)
                <div class="col-lg-4 col-xlg-3">
                    <div class="card">
                        <img class="card-img-top" src="{{asset('/assets/admin/')}}/images/background/profile-bg.jpg" alt="Card image cap">
                        <div class="card-body little-profile text-center">
                            <div class="pro-img"><img src="{{$family_member->dash_image}}" alt="user"/></div>
                            <h3 class="m-b-0">{{$family_member->dash_name}}</h3>
                            <p>{{$family_member->mobile}}</p>
                            <button href="javascript:void(0)"
                                    class="m-t-10 waves-effect waves-dark btn btn-info btn-md btn-rounded">
                                {{$family_member->dash_relation_name}}
                                ({{$family_member->dash_family_member_status_name}})
                            </button>
                        </div>
                    </div>
                </div>
                @endforeach

            @endif
        </div>

        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-body">
                    {{--            <h5 class="card-title">{{trans("language.children")}}</h5>--}}
                    <a href="{{url("admin/users/$user->id/children")}}" class="btn btn-info">
                        <h5 style="color: white ">{{trans('language.add') . ' ' . trans('language.children')}}</h5>
                    </a>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>{{trans('language.image')}}</th>
                                <th>{{trans('language.name')}}</th>
                                <th>{{trans('language.mobile')}}</th>
                                <th>{{trans('language.school')}}</th>
                                <th>{{trans('language.plan')}}</th>
                                <th>{{trans('language.birthday')}}</th>
                                <th>{{trans('language.status')}}</th>
                                <th>{{trans('language.settings')}}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($children as $item)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td> @includeIf("admin.components.image.index" , ["url" => $item->serv_image])</td>
                                    <td>{{$item->name}}</td>
                                    <td>{{$item->mobile}}</td>
                                    <td>{{optional($item->school_time->schoolLevel->school)->dash_name ? : trans('language.notSelected')  }}</td>

                                    <td>{{optional($item->order_plan_details())->dash_name ? : trans('language.notSelected')  }}</td>


                                    <td>{{$item->dash_birthday}}</td>
                                    <td>
                                        {{$item->dash_status_name}}
                                        <br>
                                        <br>
                                        @if($item->is_deleted == 0)
                                            <a class="btn btn-primary"
                                               href="{{url("admin/delete_account/$item->id")}}"> {{trans('language.remove')}} {{trans('language.account')}} </a>
                                        @else
                                            <a class="btn btn-primary"
                                               href="{{url("admin/retuen_account/$item->id")}}"> {{trans('language.retuen')}} {{trans('language.account')}} </a>
                                        @endif
                                    </td>
                                    <td>
                                        @includeIf("admin.components.buttons.delete",["message" =>  "($item->name)" ,  "action" => url("admin/users/$item->user_id/children/$item->id")])
                                        @includeIf("admin.components.buttons.custom" , ["href" => "afterSchool/$item->id", 'class' => 'default' , 'title'=> trans('language.after_school'), 'icon' => 'fa fa-list',"feather"=>'list'])
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

@endsection